apiVersion: v1
kind: Pod
metadata:
  name: grafana
  namespace: cos
spec:
  containers:
  - name: grafana
    image: grafana/grafana
    ports:
      - containerPort: 3000
    env:
      - name: GF_AUTH_ANONYMOUS_ENABLED
        value: "true"
      - name: GF_AUTH_ANONYMOUS_ORG_ROLE
        value: "Admin"
      - name: GF_USERS_DEFAULT_THEME
        value: "light"
      - name: GF_LOG_MODE
        value: "console"
      - name: GF_LOG_LEVEL
        value: "critical"
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
      - mountPath: /etc/grafana/provisioning/datasources
        name: grafana-provisioning-datasources
      - mountPath: /etc/grafana/provisioning/dashboards
        name: grafana-provisioning-dashboards
      - mountPath: /var/lib/grafana/dashboards
        name: grafana-dashboards
  volumes:
  - name: grafana-provisioning-datasources
    hostPath:
      path: /mimir/config/grafana/provisioning/datasources
      type: Directory
  - name: grafana-provisioning-dashboards
    hostPath:
      path: /mimir/config/grafana/provisioning/dashboards
      type: Directory
  - name: grafana-dashboards
    hostPath:
      path: /mimir/dashboards
      type: Directory
