apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
  namespace: cos
spec:
  selector:
    matchLabels:
      app: mimir
  serviceName: mimir
  replicas: 1
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir
        command: ["mimir"]
        args: ["-config.file=/etc/mimir/mimir.yaml"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 9009
          name: mimir-dashboard
        volumeMounts:
          - name: mimir-config
            mountPath: /etc/mimir
  volumeClaimTemplates:
  - metadata:
      name: mimir-config
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadOnlyMany" ]
      resources:
        requests:
          storage: 100M
      selector:
        matchLabels:
          type: mimir-config