apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mimir-replicas
  namespace: cos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir
        command: ["mimir"]
        args: ["-config.file=/etc/mimir/mimir.yaml"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
          - containerPort: 9009
        volumeMounts:
          - mountPath: /etc/mimir
            name: mimir-config
      volumes:
      - name: mimir-config
        hostPath:
          path: /mimir/config/mimir
          type: Directory
