apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: cos
spec:
  containers:
  - name: minio
    image: minio/minio
    command: ["minio"]
    args: ["server", "/data"]
    env:
      - name: MINIO_ACCESS_KEY
        value: mimir
      - name: MINIO_SECRET_KEY
        value: supersecret
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
      - mountPath: /data
        name: minio-data
  volumes:
  - name: minio-data
    hostPath:
      path: /mimir/data
      type: Directory
