apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: cos
  labels:
    member: mimir-cluster
spec:
  hostname: minio
  subdomain: mimir-cluster
  containers:
  - name: minio
    image: minio/minio
    command: ["minio"]
    args: ["server", "/data"]
    env:
      - name: MINIO_ACCESS_KEY
        value: mimir
      - name: MINIO_SECRET_KEY
        value: supersecret
    ports:
      - containerPort: 9000
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
      - mountPath: /data
        name: minio-data
  volumes:
  - name: minio-data
    hostPath:
      path: /home/balbir/tmp/mimir/k8s/data
      type: Directory
