apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: cos
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /etc/nginx
        name: nginx-config
  volumes:
  - name: nginx-config
    hostPath:
      path: /mimir/config/nginx
      type: Directory
