apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  namespace: cos
spec:
  containers:
  - name: prometheus
    image: prom/prometheus
    command: ["prometheus"]
    args:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --log.level=error
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    ports:
        - containerPort: 9090
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
      - mountPath: /etc/prometheus
        name: prometheus-config
  volumes:
  - name: prometheus-config
    hostPath:
      path: /mimir/config/prometheus
      type: Directory
